// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0-devel
// 	protoc        v3.12.0
// source: proto/chat.proto

package chat

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MsgInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatRoomID  uint64 `protobuf:"varint,1,opt,name=ChatRoomID,proto3" json:"ChatRoomID,omitempty"`
	UserID      uint64 `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	UserName    string `protobuf:"bytes,3,opt,name=UserName,proto3" json:"UserName,omitempty"`
	UserHeadImg string `protobuf:"bytes,4,opt,name=UserHeadImg,proto3" json:"UserHeadImg,omitempty"`
	Msg         string `protobuf:"bytes,5,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Ext         string `protobuf:"bytes,6,opt,name=Ext,proto3" json:"Ext,omitempty"`
}

func (x *MsgInfo) Reset() {
	*x = MsgInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgInfo) ProtoMessage() {}

func (x *MsgInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgInfo.ProtoReflect.Descriptor instead.
func (*MsgInfo) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{0}
}

func (x *MsgInfo) GetChatRoomID() uint64 {
	if x != nil {
		return x.ChatRoomID
	}
	return 0
}

func (x *MsgInfo) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *MsgInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *MsgInfo) GetUserHeadImg() string {
	if x != nil {
		return x.UserHeadImg
	}
	return ""
}

func (x *MsgInfo) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MsgInfo) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

var File_proto_chat_proto protoreflect.FileDescriptor

var file_proto_chat_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x63, 0x68, 0x61, 0x74, 0x22, 0xa3, 0x01, 0x0a, 0x07, 0x4d, 0x73, 0x67,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f,
	0x6f, 0x6d, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72,
	0x48, 0x65, 0x61, 0x64, 0x49, 0x6d, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x55,
	0x73, 0x65, 0x72, 0x48, 0x65, 0x61, 0x64, 0x49, 0x6d, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73,
	0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03,
	0x45, 0x78, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x45, 0x78, 0x74, 0x32, 0x3a,
	0x0a, 0x07, 0x43, 0x68, 0x61, 0x74, 0x53, 0x76, 0x72, 0x12, 0x2f, 0x0a, 0x0b, 0x53, 0x65, 0x6e,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0d, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e,
	0x4d, 0x73, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0d, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d,
	0x73, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x28, 0x01, 0x30, 0x01, 0x42, 0x12, 0x5a, 0x10, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x3b, 0x63, 0x68, 0x61, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_chat_proto_rawDescOnce sync.Once
	file_proto_chat_proto_rawDescData = file_proto_chat_proto_rawDesc
)

func file_proto_chat_proto_rawDescGZIP() []byte {
	file_proto_chat_proto_rawDescOnce.Do(func() {
		file_proto_chat_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_chat_proto_rawDescData)
	})
	return file_proto_chat_proto_rawDescData
}

var file_proto_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_chat_proto_goTypes = []interface{}{
	(*MsgInfo)(nil), // 0: chat.MsgInfo
}
var file_proto_chat_proto_depIdxs = []int32{
	0, // 0: chat.ChatSvr.SendMessage:input_type -> chat.MsgInfo
	0, // 1: chat.ChatSvr.SendMessage:output_type -> chat.MsgInfo
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_chat_proto_init() }
func file_proto_chat_proto_init() {
	if File_proto_chat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_chat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_chat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chat_proto_goTypes,
		DependencyIndexes: file_proto_chat_proto_depIdxs,
		MessageInfos:      file_proto_chat_proto_msgTypes,
	}.Build()
	File_proto_chat_proto = out.File
	file_proto_chat_proto_rawDesc = nil
	file_proto_chat_proto_goTypes = nil
	file_proto_chat_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ChatSvrClient is the client API for ChatSvr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatSvrClient interface {
	SendMessage(ctx context.Context, opts ...grpc.CallOption) (ChatSvr_SendMessageClient, error)
}

type chatSvrClient struct {
	cc grpc.ClientConnInterface
}

func NewChatSvrClient(cc grpc.ClientConnInterface) ChatSvrClient {
	return &chatSvrClient{cc}
}

func (c *chatSvrClient) SendMessage(ctx context.Context, opts ...grpc.CallOption) (ChatSvr_SendMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChatSvr_serviceDesc.Streams[0], "/chat.ChatSvr/SendMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatSvrSendMessageClient{stream}
	return x, nil
}

type ChatSvr_SendMessageClient interface {
	Send(*MsgInfo) error
	Recv() (*MsgInfo, error)
	grpc.ClientStream
}

type chatSvrSendMessageClient struct {
	grpc.ClientStream
}

func (x *chatSvrSendMessageClient) Send(m *MsgInfo) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatSvrSendMessageClient) Recv() (*MsgInfo, error) {
	m := new(MsgInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatSvrServer is the server API for ChatSvr service.
type ChatSvrServer interface {
	SendMessage(ChatSvr_SendMessageServer) error
}

// UnimplementedChatSvrServer can be embedded to have forward compatible implementations.
type UnimplementedChatSvrServer struct {
}

func (*UnimplementedChatSvrServer) SendMessage(ChatSvr_SendMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}

func RegisterChatSvrServer(s *grpc.Server, srv ChatSvrServer) {
	s.RegisterService(&_ChatSvr_serviceDesc, srv)
}

func _ChatSvr_SendMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatSvrServer).SendMessage(&chatSvrSendMessageServer{stream})
}

type ChatSvr_SendMessageServer interface {
	Send(*MsgInfo) error
	Recv() (*MsgInfo, error)
	grpc.ServerStream
}

type chatSvrSendMessageServer struct {
	grpc.ServerStream
}

func (x *chatSvrSendMessageServer) Send(m *MsgInfo) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatSvrSendMessageServer) Recv() (*MsgInfo, error) {
	m := new(MsgInfo)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ChatSvr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatSvr",
	HandlerType: (*ChatSvrServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendMessage",
			Handler:       _ChatSvr_SendMessage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/chat.proto",
}
